---
- name: "Install virtualenv"
  hosts: local
  vars_files:
    - vars.yml
  tasks:
    - name: Upgrade pip3
      shell: | 
        python3 -m pip install pip --upgrade


    - name: Create a requirements directory if it does not exist
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
        recurse: yes
      loop:
        - "{{ requirements_path }}"
        - "{{ env_path }}"
      become: yes

    - name: pull several files
      get_url:
        url: "{{ requirements_url }}/{{ item }}"
        dest: "{{ requirements_path }}"
      loop:
        - 1.txt
        - 2.txt
        - 3.txt

#for i in {1..3}; do wget "{{requirements_url}}/$i.txt";  done
    - name: Create venvs
      shell: |
        cd {{ requirements_path }};
        for FILE in *.txt; do
        [ -f "$FILE" ] || break
        ENV=$(echo $FILE | cut -d '.' -f 1)
        pip3 install virtualenv;
        virtualenv {{ env_path }}/$ENV
        source {{ env_path }}/$ENV/bin/activate
        pip3 install -r $FILE
        done