---
- name: "Install virtualenv"
  hosts: local
  become: yes
  tasks:
    - name: Install Python 3
      apt:
        name:
          - build-essential
          - python3-dev
          - libssl-dev
          - libffi-dev
        state: present

    - name: Download Pip-Installer
      get_url:
        url: https://bootstrap.pypa.io/pip/3.6/get-pip.py
        dest: /tmp/get-pip.py

    - name: Install pip
      shell: /usr/bin/python3 /tmp/get-pip.py

    - name: Create venvs
      command: |
        cd /home/runner/work/netframe/netframe/requirements;
        for FILE in *.txt; do
        [ -f "$FILE" ] || break
        pip install virtualenv;
        ENV=$(echo $FILE | cut -d '.' -f 1)
        virtualenv $ENV
        source $ENV/bin/activate
        pip install -r $FILE
        done