---
- name: "Install virtualenv"
  hosts: local
  become: yes
  tasks:
    - name: Install Python 3
      apt:
        name:
          - build-essential
          - python3-dev
          - libssl-dev
          - libffi-dev
        state: present
    - name: Upgrade pip3
      shell: python3 -m pip install pip --upgrade

    - name: Create venvs
      shell: |
        cd /home/runner/work/netframe/netframe/requirements;
        for FILE in *.txt; do
        [ -f "$FILE" ] || break
        pip install virtualenv;
        ENV=$(echo $FILE | cut -d '.' -f 1)
        virtualenv /opt/python_venvs/$ENV
        source $ENV/bin/activate
        pip install -r $FILE
        done