---
- name: "Install virtualenv"
  hosts: local
  tasks:
    - name: Upgrade pip3
      shell: python3 -m pip install pip --upgrade

    - name: Create venvs
      shell: |
        cd {{ requirements_path }}/requirements;
        for FILE in *.txt; do
        [ -f "$FILE" ] || break
        pip install virtualenv;
        ENV=$(echo $FILE | cut -d '.' -f 1)
        virtualenv env_path/$ENV
        source env_path/$ENV/bin/activate
        pip install -r $FILE
        done