---
- name: "Update virtualenv"
  hosts: local
  vars_files:
    - vars.yml
  tasks:
#    - name: discover target files
#      find:
#        paths: "{{ TARGET }}"
#        recurse: yes
#        file_type: file
#      register: TARGET_FILES
#
#    - debug:
#        var: TARGET_FILES
#
#    - name: Get stats of a file
#      stat:
#        path: "{{ item.path }}"
#        get_checksum: yes
#      loop: "{{ TARGET_FILES.files }}"
#      register: TARGET_RESULTS
#
#    - debug:
#        var: TARGET_RESULTS

    #    - name: 'write findings to log'
    #      lineinfile:
    #        line: "{{ item.stat.path }},{{ item.stat.checksum }}"
    #        path: "{{ LOG }}"
    #        create: yes
    #      loop: '{{ TARGET_RESULTS.results }}'

    #    - name: Download the last requirements file from public repo
    #      get_url:
    #        url: "{{ requirements_url }}/{{ target_files }}"
    #        dest: ~/requirements
    #        force: yes
    #        checksum: "md5:{{ item.stat.path }}|{{ item.stat.checksum }}"
    #      loop: '{{ TARGET_RESULTS.results }}'
    #      register: new

#    - name: Download the last requirements file from public repo
#      get_url:
#        url: "{{ requirements_url }}/{{ item }}"
#        dest: ~/requirements
#        force: yes
#        checksum: "md5:{{ item }}"
#      loop:
#        - 1.txt
#        - 2.txt
##        - 3.txt
##      register: new

#    - debug:
#        var: new.changed


################################################
    - name: Get stats of a file 1
      stat:
        path: "{{ requirements_path }}/1.txt"
        get_checksum: yes
        checksum_algorithm : md5
      register: TARGET_RESULTS_1

    - debug:
        var: TARGET_RESULTS_1.stat.checksum

    - name: Download the last requirements file from public repo 1
      get_url:
        url: "{{ requirements_url }}/1.txt"
        dest: ~/requirements
        force: yes
        checksum: "md5:{{ TARGET_RESULTS_1.stat.checksum }}"
      register: new_1

    - debug:
        var: new_1.changed

    - name: Update requirements
      shell: |
        source {{ env_path }}/1/bin/activate
        pip3 install -r 1.txt
      args:
        chdir: ~/requirements/
      when: "'true' in 'new_1.changed'"
####################################################
    - name: Get stats of a file 2
      stat:
        path: "{{ requirements_path }}/2.txt"
        get_checksum: yes
        checksum_algorithm : md5
      register: TARGET_RESULTS_2

    - debug:
        var: TARGET_RESULTS_2.stat.checksum

    - name: Download the last requirements file from public repo
      get_url:
        url: "{{ requirements_url }}/2.txt"
        dest: ~/requirements
        force: yes
        checksum: "md5:{{ TARGET_RESULTS_2.stat.checksum }}"
      register: new_2

    - debug:
        var: new_2.changed

    - name: Update requirements
      shell: |
        source {{ env_path }}/2/bin/activate
        pip3 install -r 2.txt
      args:
        chdir: ~/requirements/
      when: "'true' in 'new_2.changed'"

###############################################
    - name: Get stats of a file
      stat:
        path: "{{ requirements_path }}/3.txt"
        get_checksum: yes
        checksum_algorithm : md5
      register: TARGET_RESULTS_3

    - debug:
        var: TARGET_RESULTS_3.stat.checksum

    - name: Download the last requirements file from public repo
      get_url:
        url: "{{ requirements_url }}/3.txt"
        dest: ~/requirements
        force: yes
        checksum: "md5:{{ TARGET_RESULTS_3.stat.checksum }}"
      register: new_3

    - debug:
        var: new_3.changed

    - name: Update requirements
      shell: |
        source {{ env_path }}/3/bin/activate
        pip3 install -r 3.txt
      args:
        chdir: ~/requirements/
      when: "'true' in 'new_3.changed'"