name: Deploy Ansible

on:
  workflow_dispatch:

env:
  ANSIBLE_CONFIG: ansible/ansible.cfg
jobs:
  job:
    name: "Deploy"
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Dependencies
        shell: bash
        run: |
          pip3 install boto3 ansible

      - name: Run Ansible Playbook
        run: |
          ansible-playbook localhost ansible/playbook.yml -v