name: Update Virtualenv

on:
  push:
    branches:
      - 'main'
    paths:
      - 'requirements/**'
jobs:
  job:
    name: "Update Virtualenv"
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3


      - name: Install Dependencies
        shell: bash
        run: |
          sudo apt-get install build-essential python3-dev libssl-dev libffi-dev python3-virtualenv
          pip3 install ansible

      - name: Run Ansible Playbook
        run: |
          ansible-playbook -i ${{ env.ANSIBLE_INVENTORY_FILE }} ansible/update_venv_playbook.yml --extra-vars "requirements_path=$GITHUB_WORKSPACE env_path=/opt/python_venvs" -v